import { Injectable } from '@angular/core';
import { Product } from '../models/product.model';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  constructor() {}

  /* getAll(): Product[] {
    return[
      {
        id: 1,
        name: 'Green Roof Design and Installation',
        price: 1000,
        description:
          'Design and installation of green roofs for urban buildings',
        tags: ['green roof', 'sustainable', 'urban design'],
        imageUrl: '../assets/images/product-1.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['low-maintenance', 'reduces heat island effect'],
      },
      {
        id: 2,
        name: 'Urban Park Design and Construction',
        price: 50000,
        description: 'Design and construction of urban parks for public use',
        tags: ['park', 'urban design', 'public space'],
        imageUrl: '../assets/images/product-2.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['accessible', 'sustainable materials'],
      },
      {
        id: 3,
        name: 'Community garden design and management',
        price: 50000,
        description: 'We assist you in the planning of the local community garden and how it can be structured for public use',
        tags: ['garden', 'urban design', 'public space', 'management'],
        imageUrl: '../assets/images/product-3.jpg',
        categories: ['landscape architecture','park planning', 'urbanism'],
        features: ['accessible', 'sustainable materials'],
      },
      {
        id: 4,
        name: 'Streetscape design and revitalization',
        price: 50000,
        description: 'Our company provides Streetscape design and revitalization services aimed at enhancing the visual appeal, safety, and functionality of public spaces. From conceptualization to implementation, we work closely with clients to create custom solutions that transform streets and sidewalks into vibrant, pedestrian-friendly environments that attract and retain visitors, residents, and businesses.',
        tags: ['revitalization', 'urban design', 'public space', 'management'],
        imageUrl: '../assets/images/product-4.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['accessible', 'revitalization'],
      },
      {
        id: 5,
        name: 'Public plaza design and activation',
        price: 50000,
        description: 'We help activate public spaces by designing and creating unique and engaging public plazas that foster community interaction and engagement.',
        tags: ['activation', 'plaza design', 'public space', 'management'],
        imageUrl: '../assets/images/product-5.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['plaza planning', 'design'],
      },
      {
        id: 6,
        name: 'Waterfront planning and Design',
        price: 50000,
        description: 'We create sustainable and attractive waterfront spaces that prioritize natural preservation, accessibility, and recreation to provide an enjoyable experience for visitors and residents.',
        tags: ['waterfront', 'urban design', 'public space', 'management'],
        imageUrl: '../assets/images/product-6.jpg',
        categories: ['waterfront architecture', 'urbanism'],
        features: ['accessible', 'sustainable materials'],
      },
      {
        id: 7,
        name: 'Sustainable transportation infrastructure design',
        price: 50000,
        description: 'Our company offers Sustainable transportation infrastructure design services that prioritize safety, accessibility, and environmental sustainability. From bike lanes to pedestrian-friendly designs, we work with clients to create solutions that enhance mobility and reduce the environmental impact of transportation.',
        tags: ['transportation', 'infrastructure design'],
        imageUrl: '../assets/images/product-7.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['transportation', 'sustainable materials'],
      },
      {
        id: 8,
        name: 'Campus master planning and design',
        price: 50000,
        description: 'Our company provides Campus master planning and design services that help universities and colleges create sustainable and functional spaces that support the academic and social needs of students and faculty. From infrastructure planning to building design, we work with clients to create vibrant, inclusive, and forward-thinking campus environments that foster learning, innovation, and community.',
        tags: ['campus', 'urban design', 'public space', 'design'],
        imageUrl: '../assets/images/product-8.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['inclusive design', 'sustainable materials'],
      },
      {
        id: 9,
        name: 'Ecological restoration and conservation planning',
        price: 50000,
        description: 'Our company specializes in Ecological restoration and conservation planning services that prioritize the restoration and preservation of natural ecosystems. Using a science-based approach, we work with clients to create comprehensive restoration plans that address ecological degradation, mitigate environmental impacts, and promote biodiversity conservation for a sustainable future.',
        tags: ['garden', 'urban design', 'public space', 'management'],
        imageUrl: '../assets/images/product-9.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['Ecologic development'],
      },
      {
        id: 10,
        name: 'Ecological implementation of roof tiles',
        price: 50000,
        description: 'We implement tiles to cover your roof using ecological materials and installation.',
        tags: ['roof', 'eco', 'tiles', 'implementation'],
        imageUrl: '../assets/images/product-10.jpg',
        categories: ['construction', 'tiles'],
        features: ['Ecologic development'],
      },
      {
        id: 11,
        name: 'Playground design and installation',
        price: 50000,
        description: 'Our company offers Playground design and installation services that prioritize safety, creativity, and fun. From concept to construction, we work with clients to create customized playground designs that incorporate engaging play equipment, safety surfacing, and landscaping to provide children with a safe and exciting play experience.',
        tags: ['playground', 'installation', 'public space', 'design'],
        imageUrl: '../assets/images/product-11.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['accessible', 'child friendly'],
      },
      {
        id: 12,
        name: 'Civic art installation design and placement',
        price: 50000,
        description: 'Our company specializes in Civic art installation design and placement services that enhance public spaces by integrating art into the built environment. We work with clients to create innovative and meaningful art installations that celebrate community identity, promote civic engagement, and contribute to the cultural vitality of public spaces.',
        tags: ['art', 'urban design', 'public space', 'placement'],
        imageUrl: '../assets/images/product-12.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['civil art design', 'sustainable materials'],
      },
      {
        id: 13,
        name: 'Climate-responsive design and planning',
        price: 50000,
        description: 'Our company provides Climate-responsive design and planning services that prioritize resilience, sustainability, and energy efficiency. Through a holistic approach that considers climate conditions, building materials, and energy systems, we create custom solutions that reduce carbon footprint, enhance energy performance, and mitigate the impact of climate change.',
        tags: ['urban design', 'public space', 'management'],
        imageUrl: '../assets/images/product-13.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['Climate friendly', 'sustainable materials'],
      },
      {
        id: 14,
        name: 'Wayfinding and signage system design',
        price: 50000,
        description: 'Our company offers Wayfinding and signage system design services that improve navigation and accessibility in public spaces. From conceptualization to implementation, we work with clients to create custom wayfinding and signage systems that incorporate design, materials, and technology to provide clear and concise directions, enhance the user experience, and promote efficient movement through complex environments.',
        tags: ['garden', 'urban design', 'public space', 'management'],
        imageUrl: '../assets/images/product-14.jpg',
        categories: ['Wayfinding', 'system design'],
        features: ['Management consulting', 'sustainable materials'],
      },
      {
        id: 15,
        name: 'Biophilic design and planning',
        price: 50000,
        description: 'Our company specializes in Biophilic design and planning services that prioritize the integration of nature into the built environment. From urban landscapes to indoor spaces, we work with clients to create sustainable designs that incorporate natural elements such as daylight, greenery, and water features to enhance human health and wellbeing, reduce stress, and increase productivity.',
        tags: ['Bio planning', 'urban design', 'public space', 'management'],
        imageUrl: '../assets/images/product-15.jpg',
        categories: ['landscape architecture', 'urbanism'],
        features: ['Biofilic Design', 'sustainable materials'],
      }
    ]
  } */

  products: Product[]=[
    {
      id: 1,
      name: 'Green Roof Design and Installation',
      price: 1000,
      description:
        'Design and installation of green roofs for urban buildings',
      tags: ['green roof', 'sustainable', 'urban design'],
      imageUrl: '../assets/images/product-1.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['low-maintenance', 'reduces heat island effect'],
    },
    {
      id: 2,
      name: 'Urban Park Design and Construction',
      price: 50000,
      description: 'Design and construction of urban parks for public use',
      tags: ['park', 'urban design', 'public space'],
      imageUrl: '../assets/images/product-2.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['accessible', 'sustainable materials'],
    },
    {
      id: 3,
      name: 'Community garden design and management',
      price: 50000,
      description: 'We assist you in the planning of the local community garden and how it can be structured for public use',
      tags: ['garden', 'urban design', 'public space', 'management'],
      imageUrl: '../assets/images/product-3.jpg',
      categories: ['landscape architecture','park planning', 'urbanism'],
      features: ['accessible', 'sustainable materials'],
    },
    {
      id: 4,
      name: 'Streetscape design and revitalization',
      price: 50000,
      description: 'Our company provides Streetscape design and revitalization services aimed at enhancing the visual appeal, safety, and functionality of public spaces. From conceptualization to implementation, we work closely with clients to create custom solutions that transform streets and sidewalks into vibrant, pedestrian-friendly environments that attract and retain visitors, residents, and businesses.',
      tags: ['revitalization', 'urban design', 'public space', 'management'],
      imageUrl: '../assets/images/product-4.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['accessible', 'revitalization'],
    },
    {
      id: 5,
      name: 'Public plaza design and activation',
      price: 50000,
      description: 'We help activate public spaces by designing and creating unique and engaging public plazas that foster community interaction and engagement.',
      tags: ['activation', 'plaza design', 'public space', 'management'],
      imageUrl: '../assets/images/product-5.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['plaza planning', 'design'],
    },
    {
      id: 6,
      name: 'Waterfront planning and Design',
      price: 50000,
      description: 'We create sustainable and attractive waterfront spaces that prioritize natural preservation, accessibility, and recreation to provide an enjoyable experience for visitors and residents.',
      tags: ['waterfront', 'urban design', 'public space', 'management'],
      imageUrl: '../assets/images/product-6.jpg',
      categories: ['waterfront architecture', 'urbanism'],
      features: ['accessible', 'sustainable materials'],
    },
    {
      id: 7,
      name: 'Sustainable transportation infrastructure design',
      price: 50000,
      description: 'Our company offers Sustainable transportation infrastructure design services that prioritize safety, accessibility, and environmental sustainability. From bike lanes to pedestrian-friendly designs, we work with clients to create solutions that enhance mobility and reduce the environmental impact of transportation.',
      tags: ['transportation', 'infrastructure design'],
      imageUrl: '../assets/images/product-7.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['transportation', 'sustainable materials'],
    },
    {
      id: 8,
      name: 'Campus master planning and design',
      price: 50000,
      description: 'Our company provides Campus master planning and design services that help universities and colleges create sustainable and functional spaces that support the academic and social needs of students and faculty. From infrastructure planning to building design, we work with clients to create vibrant, inclusive, and forward-thinking campus environments that foster learning, innovation, and community.',
      tags: ['campus', 'urban design', 'public space', 'design'],
      imageUrl: '../assets/images/product-8.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['inclusive design', 'sustainable materials'],
    },
    {
      id: 9,
      name: 'Ecological restoration and conservation planning',
      price: 50000,
      description: 'Our company specializes in Ecological restoration and conservation planning services that prioritize the restoration and preservation of natural ecosystems. Using a science-based approach, we work with clients to create comprehensive restoration plans that address ecological degradation, mitigate environmental impacts, and promote biodiversity conservation for a sustainable future.',
      tags: ['garden', 'urban design', 'public space', 'management'],
      imageUrl: '../assets/images/product-9.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['Ecologic development'],
    },
    {
      id: 10,
      name: 'Ecological implementation of roof tiles',
      price: 50000,
      description: 'We implement tiles to cover your roof using ecological materials and installation.',
      tags: ['roof', 'eco', 'tiles', 'implementation'],
      imageUrl: '../assets/images/product-10.jpg',
      categories: ['construction', 'tiles'],
      features: ['Ecologic development'],
    },
    {
      id: 11,
      name: 'Playground design and installation',
      price: 50000,
      description: 'Our company offers Playground design and installation services that prioritize safety, creativity, and fun. From concept to construction, we work with clients to create customized playground designs that incorporate engaging play equipment, safety surfacing, and landscaping to provide children with a safe and exciting play experience.',
      tags: ['playground', 'installation', 'public space', 'design'],
      imageUrl: '../assets/images/product-11.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['accessible', 'child friendly'],
    },
    {
      id: 12,
      name: 'Civic art installation design and placement',
      price: 50000,
      description: 'Our company specializes in Civic art installation design and placement services that enhance public spaces by integrating art into the built environment. We work with clients to create innovative and meaningful art installations that celebrate community identity, promote civic engagement, and contribute to the cultural vitality of public spaces.',
      tags: ['art', 'urban design', 'public space', 'placement'],
      imageUrl: '../assets/images/product-12.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['civil art design', 'sustainable materials'],
    },
    {
      id: 13,
      name: 'Climate-responsive design and planning',
      price: 50000,
      description: 'Our company provides Climate-responsive design and planning services that prioritize resilience, sustainability, and energy efficiency. Through a holistic approach that considers climate conditions, building materials, and energy systems, we create custom solutions that reduce carbon footprint, enhance energy performance, and mitigate the impact of climate change.',
      tags: ['urban design', 'public space', 'management'],
      imageUrl: '../assets/images/product-13.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['Climate friendly', 'sustainable materials'],
    },
    {
      id: 14,
      name: 'Wayfinding and signage system design',
      price: 50000,
      description: 'Our company offers Wayfinding and signage system design services that improve navigation and accessibility in public spaces. From conceptualization to implementation, we work with clients to create custom wayfinding and signage systems that incorporate design, materials, and technology to provide clear and concise directions, enhance the user experience, and promote efficient movement through complex environments.',
      tags: ['garden', 'urban design', 'public space', 'management'],
      imageUrl: '../assets/images/product-14.jpg',
      categories: ['Wayfinding', 'system design'],
      features: ['Management consulting', 'sustainable materials'],
    },
    {
      id: 15,
      name: 'Biophilic design and planning',
      price: 50000,
      description: 'Our company specializes in Biophilic design and planning services that prioritize the integration of nature into the built environment. From urban landscapes to indoor spaces, we work with clients to create sustainable designs that incorporate natural elements such as daylight, greenery, and water features to enhance human health and wellbeing, reduce stress, and increase productivity.',
      tags: ['Bio planning', 'urban design', 'public space', 'management'],
      imageUrl: '../assets/images/product-15.jpg',
      categories: ['landscape architecture', 'urbanism'],
      features: ['Biofilic Design', 'sustainable materials'],
    }
  ];

  getAll(){
    return this.products;
  }

  getProduct(productId: number) {
    const product = this.products.find((p) => p.id === productId);
    return product || null;
  }
}

